/*
 * Created on 2019-06-28 ( Date ISO 2019-06-28 - Time 08:07:05 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package org.demo.data.record;

import java.io.Serializable;
import javax.validation.constraints.*;


/**
 * Java bean for entity "admin" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class AdminRecord implements Serializable
{
    private static final long serialVersionUID = 1L;

    @NotNull
    private Integer id ; // Integer // Id or Primary Key

    @Size( max = 50 )
    private String namead ;  // String 
    @Size( max = 50 )
    private String userad ;  // String 
    @Size( max = 50 )
    private String passad ;  // String 

    /**
     * Default constructor
     */
    public AdminRecord() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "INT", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "namead" field value
     * This field is mapped on the database column "nameAd" ( type "VARCHAR", NotNull : false ) 
     * @param namead
     */
    public void setNamead( String namead ) {
        this.namead = namead;
    }
    /**
     * Get the "namead" field value
     * This field is mapped on the database column "nameAd" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getNamead() {
        return this.namead;
    }

    /**
     * Set the "userad" field value
     * This field is mapped on the database column "userAd" ( type "VARCHAR", NotNull : false ) 
     * @param userad
     */
    public void setUserad( String userad ) {
        this.userad = userad;
    }
    /**
     * Get the "userad" field value
     * This field is mapped on the database column "userAd" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getUserad() {
        return this.userad;
    }

    /**
     * Set the "passad" field value
     * This field is mapped on the database column "passAd" ( type "VARCHAR", NotNull : false ) 
     * @param passad
     */
    public void setPassad( String passad ) {
        this.passad = passad;
    }
    /**
     * Get the "passad" field value
     * This field is mapped on the database column "passAd" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getPassad() {
        return this.passad;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(namead);
        sb.append("|");
        sb.append(userad);
        sb.append("|");
        sb.append(passad);
        return sb.toString(); 
    } 



}
