/*
 * Created on 2019-06-28 ( Date ISO 2019-06-28 - Time 08:07:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package org.demo.data.record;

import java.io.Serializable;
import javax.validation.constraints.*;


/**
 * Java bean for entity "scores" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class ScoresRecord implements Serializable
{
    private static final long serialVersionUID = 1L;

    @NotNull
    private Integer id ; // Integer // Id or Primary Key


    private Integer studentid ;  // Integer 

    private Integer subjectid ;  // Integer 

    private Double score ;  // Double 

    /**
     * Default constructor
     */
    public ScoresRecord() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "INT", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "studentid" field value
     * This field is mapped on the database column "studentId" ( type "INT", NotNull : false ) 
     * @param studentid
     */
    public void setStudentid( Integer studentid ) {
        this.studentid = studentid;
    }
    /**
     * Get the "studentid" field value
     * This field is mapped on the database column "studentId" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getStudentid() {
        return this.studentid;
    }

    /**
     * Set the "subjectid" field value
     * This field is mapped on the database column "subjectId" ( type "INT", NotNull : false ) 
     * @param subjectid
     */
    public void setSubjectid( Integer subjectid ) {
        this.subjectid = subjectid;
    }
    /**
     * Get the "subjectid" field value
     * This field is mapped on the database column "subjectId" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getSubjectid() {
        return this.subjectid;
    }

    /**
     * Set the "score" field value
     * This field is mapped on the database column "score" ( type "DOUBLE", NotNull : false ) 
     * @param score
     */
    public void setScore( Double score ) {
        this.score = score;
    }
    /**
     * Get the "score" field value
     * This field is mapped on the database column "score" ( type "DOUBLE", NotNull : false ) 
     * @return the field value
     */
    public Double getScore() {
        return this.score;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(studentid);
        sb.append("|");
        sb.append(subjectid);
        sb.append("|");
        sb.append(score);
        return sb.toString(); 
    } 



}
