/*
 * Created on 2019-06-28 ( Date ISO 2019-06-28 - Time 08:07:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
 */


package org.demo.data.record;

import java.io.Serializable;
import javax.validation.constraints.*;


/**
 * Java bean for entity "subjects" <br>
 * Contains only "wrapper types" (no primitive types) <br>
 * Can be used both as a "web form" and "persistence record" <br>
 * 
 * @author Telosys Tools Generator
 *
 */
public class SubjectsRecord implements Serializable
{
    private static final long serialVersionUID = 1L;

    @NotNull
    private Integer id ; // Integer // Id or Primary Key

    @Size( max = 50 )
    private String namesu ;  // String 
    @Size( max = 50 )
    private String codesu ;  // String 

    private Integer factor ;  // Integer 
    @Size( max = 50 )
    private String note ;  // String 

    /**
     * Default constructor
     */
    public SubjectsRecord() {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR ID OR PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "INT", NotNull : true ) 
     * @param id
     */
	public void setId( Integer id ) {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "INT", NotNull : true ) 
     * @return the field value
     */
	public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR OTHER DATA FIELDS 
    //----------------------------------------------------------------------

    /**
     * Set the "namesu" field value
     * This field is mapped on the database column "nameSu" ( type "VARCHAR", NotNull : false ) 
     * @param namesu
     */
    public void setNamesu( String namesu ) {
        this.namesu = namesu;
    }
    /**
     * Get the "namesu" field value
     * This field is mapped on the database column "nameSu" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getNamesu() {
        return this.namesu;
    }

    /**
     * Set the "codesu" field value
     * This field is mapped on the database column "codeSu" ( type "VARCHAR", NotNull : false ) 
     * @param codesu
     */
    public void setCodesu( String codesu ) {
        this.codesu = codesu;
    }
    /**
     * Get the "codesu" field value
     * This field is mapped on the database column "codeSu" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getCodesu() {
        return this.codesu;
    }

    /**
     * Set the "factor" field value
     * This field is mapped on the database column "factor" ( type "INT", NotNull : false ) 
     * @param factor
     */
    public void setFactor( Integer factor ) {
        this.factor = factor;
    }
    /**
     * Get the "factor" field value
     * This field is mapped on the database column "factor" ( type "INT", NotNull : false ) 
     * @return the field value
     */
    public Integer getFactor() {
        return this.factor;
    }

    /**
     * Set the "note" field value
     * This field is mapped on the database column "note" ( type "VARCHAR", NotNull : false ) 
     * @param note
     */
    public void setNote( String note ) {
        this.note = note;
    }
    /**
     * Get the "note" field value
     * This field is mapped on the database column "note" ( type "VARCHAR", NotNull : false ) 
     * @return the field value
     */
    public String getNote() {
        return this.note;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    @Override
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(namesu);
        sb.append("|");
        sb.append(codesu);
        sb.append("|");
        sb.append(factor);
        sb.append("|");
        sb.append(note);
        return sb.toString(); 
    } 



}
